import * as esbuild from 'esbuild';
import { existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes('--watch');

// Entry points for each bundle
const entryPoints = {
  'project-bundle': 'static/ts/project/index.ts',
  'edit-bundle': 'static/ts/edit/index.ts',
};

// Filter to only existing entry points
const existingEntries = Object.entries(entryPoints)
  .filter(([_, path]) => existsSync(join(__dirname, path)))
  .reduce((acc, [name, path]) => ({ ...acc, [name]: path }), {});

if (Object.keys(existingEntries).length === 0) {
  console.log('No entry points found yet. Create TypeScript files to start building.');
  process.exit(0);
}

/** @type {esbuild.BuildOptions} */
const buildOptions = {
  entryPoints: existingEntries,
  bundle: true,
  outdir: 'static/js',
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  sourcemap: true,
  minify: !isWatch,
  metafile: true,
  logLevel: 'info',

  // Define globals for external libraries
  define: {
    'process.env.NODE_ENV': isWatch ? '"development"' : '"production"',
  },

  // Banner to expose modules to window
  banner: {
    js: '// Auto-generated by esbuild - do not edit directly\n',
  },

  // Footer to handle exports
  footer: {
    js: '',
  },

  plugins: [
    {
      name: 'build-notifications',
      setup(build) {
        build.onStart(() => {
          console.log(`\n[${new Date().toLocaleTimeString()}] Building...`);
        });
        build.onEnd((result) => {
          if (result.errors.length > 0) {
            console.error(`Build failed with ${result.errors.length} error(s)`);
          } else {
            console.log(`Build completed successfully`);
            if (result.metafile) {
              const outputs = Object.entries(result.metafile.outputs);
              for (const [file, meta] of outputs) {
                if (file.endsWith('.js')) {
                  const sizeKB = (meta.bytes / 1024).toFixed(1);
                  console.log(`  ${file}: ${sizeKB} KB`);
                }
              }
            }
          }
        });
      },
    },
  ],
};

async function build() {
  try {
    if (isWatch) {
      const ctx = await esbuild.context(buildOptions);
      await ctx.watch();
      console.log('Watching for changes...');
    } else {
      await esbuild.build(buildOptions);
    }
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

build();
